name: chenbin_app
description: WMS 仓储管理系统

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  permission_handler: ^11.0.1
  barcode_scan2: ^4.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: PingFang
      fonts:
        - asset: fonts/PingFang-Regular.ttf
        - asset: fonts/PingFang-Medium.ttf
          weight: 500